name: automate-DESDEO-problem

on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip

  test:
    strategy:
      fail-fast: false  # Allow retries
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.8", "3.9" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
          
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
        
      - name: Install library
        run: poetry install --no-interaction

      - name: Run tests
        id: run-tests
        run: |
          source .venv/bin/activate
          pytest tests/
          #coverage report
      
      - name: Retry tests on failure
        if: ${{ failure() }}
        run: |
          echo "Retrying failed tests..."
          source .venv/bin/activate
          pytest tests/
          #coverage report
          
      #Some changes here too
     # - name: Fetch master branch
     #   run: git fetch origin master
      
      #Needs some changes here
     # - name: Merge to master
     #   if: ${{ success() }}
     #   run: |
     #     #These need to be changed later
     #     git config user.name Severi_Nattila
     #     git config user.email severi.nattila@gmail.com
     #     git checkout master
     #     git merge --no-ff ${{ github.head_ref }}
     #     git push origin master




