name: Problem Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_test_problem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Add more steps here based on your build and test requirements for the problem repository

      - name: Trigger Main Repository Workflow
        uses: peter-evans/trigger-workflow@v2
        with:
          workflow: "Main Repository Workflow"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          event-type: update_main_branch
