name: automate-DESDEO-problem

on:
  pull_request:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/
          # Add any additional test-related commands or steps here

      - name: Update main branch
        if: ${{ success() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update main branch'
          branch: main
          

  update_desdeo:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DESDEO-main workflow
        uses: peter-evans/trigger-workflow@v2
        with:
          workflow: DESDEO-main.yml
          token: ${{ secrets.PAT_DESDEO }}
          repository: DESDEO
          ref: main



